<?php $action = $this->getAction();
$action = $action[0];
$list = scandir(VIEW);
$listq = count($list);
while($listq>0){
	$listq--;
	$listtmp = $list[$listq];
	if(substr($listtmp,-5)!='phtml' && substr($listtmp,-1)!='.') 
	{
	    echo $list[$listq]."|";
	}
}
?>

<!DOCTYPE html>
<html>
<head>
<meta charset = "UTF-8">
<link rel = "stylesheet" href = '../public/style.css'  type = "text/css" media = "all">

<script src="../public/jquery-3.5.1.js"></script>
<title><?php echo (isset($this->page_title) ? $this->page_title : 'Connegence-iot'); ?></title>
</head>
<body>
</div class="web-frame">
<h2>ZTD Company</h2>

<hr class = "ztd-header-hr"/>

<div id='bannerlist-div'>
	<nav class='bannerlist-ul'>
		<ul>
			<li><a href = "/home/index" <?php echo $action =='home'? 'class=active' : '' ?> >Home</a></li>
			<li><a href = "/IMEI/ImeiIndex" <?php echo $action =='IMEI'? 'class=active' : '' ?> id = 'ImeiIndex' >IMEI</a></li>
			<li><a href = "/Project/ProjectIndex" <?php echo $action =='Project'? 'class=active' : '' ?> id = 'ProjectIndex' >Project</a></li>
			<?php 
			
			
			?>
		</ul>
	</nav>
</div>

<hr class = "ztd-header-hr"/>

<div class = "sidebar-div" id = 'sidebar-right'></div>