<h1>Project Manager Page</h1>
<!--------project list---------------------------------->
<nav>
<ul>
<li><a href = "/IMEI/imeiSearch">Project Add</a></li>
<li><a href = "/IMEI/imeiSearch">Project Del</a></li>
<li><a href = "/IMEI/imeiSearch">Project Update</a></li>
</ul>    
</nav> 
<div>
			<label>Select a Project to Show Detail</label>
			<form> 
				<select name="Project" id="ZTDProjectsel"  onchange='getform()'autofocus>
					<?php 
                    $data = $this->view_data;
                    
					for($i=0;$i<count($data);$i++) {

						echo "<option value=".$data[$i][0].">".$data[$i][1].' ( '.$data[$i][6].' ) '."</option>";
						
					}
					?>
                </select>
                <table class='projecttable'>




                </table>
			</form>
		</div>