<h1>New Project</h1>


<div class='projectnew-main-div'>

    <div class='projectnew-div'>
        <div class='projectnewlabel-div'>
            <label class='projectnew-label'>新增專案編號:</label><br/>
            <label class='projectnew-label'>專案負責人:</label><br/>
            <div class="projectproductselected-div"><label class='projectnew-label'>產品:</label><br/></div>
        </div>
    
        <div class='projectnewinput-div'>
            <input type = 'text' id = 'projectid-new' class='projectnew-input'required><br/>
            <input type = 'text' id = 'project-new' class='projectnew-input' required><br/>
            <div class="projectproductselected-div">
                <select id='projectproductselected' class='projectnew-select'>
                    <option value='new'>新產品</option selectded>
                    <option value='old'>現有產品</option >
                </select><br/>
            </div>   
        </div>   
    </div>

    <div class='productselected-table-div'></div><br/> 
    
</div>        